declare module "@editorjs/header";
declare module "@editorjs/list";
declare module "@editorjs/code";
declare module "@editorjs/link";
declare module "@editorjs/inline-code";
declare module "@editorjs/simple-image";
declare module "@editorjs/embed";
declare module "@editorjs/image";
declare module "@editorjs/table";
